<?php

namespace Adena\MailBundle\Repository;

use Adena\MailBundle\Entity\Campaign;

/**
 * CampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     *
     * @return \Adena\MailBundle\Entity\Campaign
     */
    public function getWithEmail($id){
        return $this->createQueryBuilder('c')
            ->join('c.email', 'e')
            ->addSelect('e')
            ->where('c.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();
    }
}
