<?php

namespace Adena\MailBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends \Doctrine\ORM\EntityRepository
{

    public function getEmailsQuery()
    {
        $query = $this
            ->createQueryBuilder('e')
            ->orderBy('e.createdAt', 'desc')
            ->getQuery();

        return $query;
    }

}
