<?php

namespace Adena\MailBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends \Doctrine\ORM\EntityRepository
{

    public function getEmailsQuery()
    {
        $query = $this->getEmailsQueryBuilder()
            ->getQuery();

        return $query;
    }

    public function getEmailsQueryBuilder($whereName = false)
    {
        $queryBuilder = $this
            ->createQueryBuilder('e')
            ->orderBy('e.createdAt', 'desc');

        if($whereName)
        {
            $queryBuilder->where('e.name LIKE :name')
                ->setParameter('name', '%'.$whereName.'%');
        }

        return $queryBuilder;
    }

}
