<?php

namespace Adena\MailBundle\Repository;

/**
 * SendersListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SendersListRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSendersListsQuery()
    {
        $query = $this->getSendersListsQueryBuilder()
            ->getQuery();

        return $query;
    }

    public function getWithSenders($id){
        return $this
            ->createQueryBuilder('sl')
            ->join('sl.senders', 's')
            ->addSelect('s')
            ->where('sl.id = :id')
            ->setParameter('id', $id)
            ->andWhere('s.active = :active')
            ->setParameter('active', 1)
            ->getQuery()
            ->getSingleResult();
    }

    public function getSendersListsQueryBuilder()
    {
        $queryBuilder = $this
            ->createQueryBuilder('sl')
            ->orderBy('sl.name', 'asc');

        return $queryBuilder;
    }
}
