<?php

namespace Adena\MailBundle\Repository;

/**
 * SendersListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SendersListRepository extends \Doctrine\ORM\EntityRepository
{
}
