<?php

namespace Adena\MailBundle\Repository;

/**
 * SenderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SenderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSendersQuery()
    {
        $query = $this
            ->createQueryBuilder('s')
            ->orderBy('s.name', 'desc')
            ->getQuery();

        return $query;
    }
}
