adena_test:
    resource: "@AdenaTestBundle/Resources/config/routing.yml"
    prefix:   /

adena_paginator:
    resource: "@AdenaPaginatorBundle/Resources/config/routing.yml"
    prefix:   /

adena_core:
    resource: "@AdenaCoreBundle/Resources/config/routing.yml"
    prefix:   /

adena_mail:
    resource: "@AdenaMailBundle/Resources/config/routing.yml"
    prefix:   /
