services:
  adena_test.fixtures_loader:
    class: Adena\TestBundle\FixturesLoader\FixturesLoader
    arguments: ['@doctrine.orm.default_entity_manager', '%kernel.root_dir%', '%kernel.bundles_metadata%']

