<?php

namespace Adena\MailBundle\Tests\EntityHelper;

use Adena\MailBundle\Entity\Campaign;
use Adena\MailBundle\Entity\Email;
use Adena\MailBundle\Entity\MailingList;
use Adena\MailBundle\EntityHelper\CampaignTester;
use Adena\MailBundle\EntityHelper\MailingListDataFetcher;
use Adena\TestBundle\ORMTestHelper\ORMTestHelper;
use Symfony\Bundle\FrameworkBundle\Tests\TestCase;

class CampaignTesterTest extends TestCase
{

    private $campaign;
    private $twig;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $mailingList = new MailingList();
        $mailingList->setName("TestMailingList");

        $email = new Email();
        $email->setTemplate('{{ name }} {{ anotherfield }}');

        $this->campaign = new Campaign();
        $this->campaign->addMailingList(
            $mailingList
        );
        $this->campaign->setEmail($email);

        $this->twig = new \Twig_Environment(new \Twig_Loader_Array());
    }


    public function testTestSuccess()
    {
        $dataFetcher = $this->createMock(MailingListDataFetcher::class);
        $dataFetcher->expects($this->any())
                    ->method('getFirstRow')
                    ->will($this->returnValue([
                        'email'=>'test@example.com',
                        'name'=>'Testy test',
                        'anotherfield'=>'field data'
                    ]));

        $campaignTester = new CampaignTester($this->twig, $dataFetcher);
        $this->assertTrue($campaignTester->test($this->campaign));
    }

    public function testTestMissingVariable()
    {
        $dataFetcher = $this->createMock(MailingListDataFetcher::class);
        $dataFetcher->expects($this->any())
            ->method('getFirstRow')
            ->will($this->returnValue([
                'email'=>'test@example.com',
                'name'=>'Testy test'
            ]));

        $campaignTester = new CampaignTester($this->twig, $dataFetcher);
        $this->expectExceptionMessage('Variable "anotherfield" does not exist in the MailingList: TestMailingList');
        $campaignTester->test($this->campaign);
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        $this->twig = null;
        $this->campaign = null;
    }
}