adena_mail_homepage:
    path:     /
    defaults: { _controller: AdenaMailBundle:Home:index }

adena_mail_sender_list:
    path:     /sender
    defaults: { _controller: AdenaMailBundle:Sender:list }

adena_mail_sender_add:
    path:     /sender/add
    defaults: { _controller: AdenaMailBundle:Sender:add }

adena_mail_sender_edit:
    path:     /sender/edit/{id}
    defaults: { _controller: AdenaMailBundle:Sender:edit }
    requirements:
        id: \d+

adena_mail_sender_delete:
    path:     /sender/delete/{id}
    defaults: { _controller: AdenaMailBundle:Sender:delete }
    requirements:
        id: \d+


adena_mail_email_add:
  path: /email/add
  defaults:
    _controller: AdenaMailBundle:Email:add

adena_mail_email_view:
  path: /email/{id}
  defaults:
    _controller: AdenaMailBundle:Email:view
  requirements:
    id: \d+

adena_mail_email_edit:
  path: /email/edit/{id}
  defaults:
    _controller: AdenaMailBundle:Email:edit
  requirements:
    id: \d+

adena_mail_email_delete:
  path: /email/delete/{id}
  defaults:
    _controller: AdenaMailBundle:Email:delete
  requirements:
    id: \d+

adena_mail_email_list:
  path: /email
  defaults:
    _controller: AdenaMailBundle:Email:list


adena_mail_mailing_list_add:
  path: /mailing-list/add/{type}
  defaults:
    _controller: AdenaMailBundle:MailingList:add
    type: query

adena_mail_mailing_list_view:
  path: /mailing-list/{id}
  defaults:
    _controller: AdenaMailBundle:MailingList:view
  requirements:
    id: \d+

adena_mail_mailing_list_edit:
  path: /mailing-list/edit/{id}
  defaults:
    _controller: AdenaMailBundle:MailingList:edit
  requirements:
    id: \d+

adena_mail_mailing_list_delete:
  path: /mailing-list/delete/{id}
  defaults:
    _controller: AdenaMailBundle:MailingList:delete
  requirements:
    id: \d+

adena_mail_mailing_list_list:
  path: /mailing-list
  defaults:
    _controller: AdenaMailBundle:MailingList:list

adena_mail_mailing_list_choose_add:
  path: /mailing-list/choose-add
  defaults:
    _controller: AdenaMailBundle:MailingList:chooseAdd

adena_mail_datasource_list:
    path:     /datasource
    defaults: { _controller: AdenaMailBundle:Datasource:list }

adena_mail_datasource_add:
    path:     /datasource/add
    defaults: { _controller: AdenaMailBundle:Datasource:add }

adena_mail_datasource_edit:
    path:     /datasource/edit/{id}
    defaults: { _controller: AdenaMailBundle:Datasource:edit }
    requirements:
        id: \d+

adena_mail_datasource_delete:
    path:     /datasource/delete/{id}
    defaults: { _controller: AdenaMailBundle:Datasource:delete }
    requirements:
        id: \d+

adena_mail_xhr_validation:
  path: /xhr/validation
  defaults: { _controller: AdenaMailBundle:MailingList:xhrValidation }
  methods: [POST]