adena_mail_homepage:
    path:     /
    defaults: { _controller: AdenaMailBundle:Home:index }

adena_mail_sender_list:
    path:     /sender/{page}
    defaults:
      _controller: AdenaMailBundle:Sender:list
      page: 1
    requirements:
      page: \d*

adena_mail_sender_add:
    path:     /sender/add
    defaults: { _controller: AdenaMailBundle:Sender:add }

adena_mail_sender_edit:
    path:     /sender/edit/{id}
    defaults: { _controller: AdenaMailBundle:Sender:edit }
    requirements:
        id: \d+

adena_mail_sender_delete:
    path:     /sender/delete/{id}
    defaults: { _controller: AdenaMailBundle:Sender:delete }
    requirements:
        id: \d+


adena_mail_email_add:
  path: /email/add
  defaults:
    _controller: AdenaMailBundle:Email:add

adena_mail_email_view:
  path: /email/view/{id}
  defaults:
    _controller: AdenaMailBundle:Email:view
  requirements:
    id: \d+

adena_mail_email_edit:
  path: /email/edit/{id}
  defaults:
    _controller: AdenaMailBundle:Email:edit
  requirements:
    id: \d+

adena_mail_email_delete:
  path: /email/delete/{id}
  defaults:
    _controller: AdenaMailBundle:Email:delete
  requirements:
    id: \d+

adena_mail_email_list:
  path: /email/{page}
  defaults:
    _controller: AdenaMailBundle:Email:list
    page: 1
  requirements:
    page: \d*

adena_mail_mailing_list_add:
  path: /mailing-list/add/{type}
  defaults:
    _controller: AdenaMailBundle:MailingList:add
    type: query

adena_mail_mailing_list_view:
  path: /mailing-list/view/{id}
  defaults:
    _controller: AdenaMailBundle:MailingList:view
  requirements:
    id: \d+

adena_mail_mailing_list_edit:
  path: /mailing-list/edit/{id}
  defaults:
    _controller: AdenaMailBundle:MailingList:edit
  requirements:
    id: \d+

adena_mail_mailing_list_delete:
  path: /mailing-list/delete/{id}
  defaults:
    _controller: AdenaMailBundle:MailingList:delete
  requirements:
    id: \d+

adena_mail_mailing_list_test:
  path: /mailing-list/test/{id}
  defaults:
    _controller: AdenaMailBundle:MailingList:test
  requirements:
    id: \d+

adena_mail_mailing_list_list:
  path: /mailing-list/{page}
  defaults:
    _controller: AdenaMailBundle:MailingList:list
    page: 1
  requirements:
    page: \d*

adena_mail_mailing_list_choose_add:
  path: /mailing-list/choose-add
  defaults:
    _controller: AdenaMailBundle:MailingList:chooseAdd

adena_mail_senders_list_list:
    path:     /senders-list/{page}
    defaults:
      _controller: AdenaMailBundle:SendersList:list
      page: 1
    requirements:
      page: \d*

adena_mail_senders_list_add:
    path:     /senders-list/add
    defaults: { _controller: AdenaMailBundle:SendersList:add }

adena_mail_senders_list_edit:
    path:     /senders-list/edit/{id}
    defaults: { _controller: AdenaMailBundle:SendersList:edit }
    requirements:
        id: \d+

adena_mail_senders_list_delete:
    path:     /senders-list/delete/{id}
    defaults: { _controller: AdenaMailBundle:SendersList:delete }
    requirements:
        id: \d+

adena_mail_datasource_list:
    path:     /datasource/{page}
    defaults:
      _controller: AdenaMailBundle:Datasource:list
      page: 1
    requirements:
      page: \d*

adena_mail_datasource_add:
    path:     /datasource/add
    defaults: { _controller: AdenaMailBundle:Datasource:add }

adena_mail_datasource_edit:
    path:     /datasource/edit/{id}
    defaults: { _controller: AdenaMailBundle:Datasource:edit }
    requirements:
        id: \d+

adena_mail_datasource_delete:
    path:     /datasource/delete/{id}
    defaults: { _controller: AdenaMailBundle:Datasource:delete }
    requirements:
        id: \d+

adena_mail_campaign_list:
    path:     /campaign/{page}
    defaults:
      _controller: AdenaMailBundle:Campaign:list
      page: 1
      showCompleted: false
    requirements:
      page: \d*

adena_mail_campaign_completed_list:
    path:     /campaign/completed/{page}
    defaults:
      _controller: AdenaMailBundle:Campaign:list
      page: 1
      showCompleted: true
    requirements:
      page: \d*

adena_mail_campaign_add:
    path:     /campaign/add
    defaults: { _controller: AdenaMailBundle:Campaign:add }

adena_mail_campaign_edit:
    path:     /campaign/edit/{id}
    defaults: { _controller: AdenaMailBundle:Campaign:edit }
    requirements:
        id: \d+

adena_mail_campaign_delete:
    path:     /campaign/delete/{id}
    defaults: { _controller: AdenaMailBundle:Campaign:delete }
    requirements:
        id: \d+

adena_mail_campaign_view:
  path: /campaign/view/{id}
  defaults: { _controller: AdenaMailBundle:Campaign:view }
  requirements:
      id: \d+

adena_mail_campaign_send:
  path: /campaign/send/{id}
  defaults: { _controller: AdenaMailBundle:Campaign:send }
  requirements:
      id: \d+

adena_mail_campaign_pause:
  path: /campaign/pause/{id}
  defaults: { _controller: AdenaMailBundle:Campaign:pause }
  requirements:
      id: \d+

adena_mail_campaign_test:
  path: /campaign/test/{id}
  defaults: { _controller: AdenaMailBundle:Campaign:test }
  requirements:
      id: \d+

adena_mail_xhr_validation:
  path: /xhr/validation
  defaults: { _controller: AdenaMailBundle:Xhr:validation }
  methods: [POST]