adena_mail_homepage:
    path:     /
    defaults: { _controller: AdenaMailBundle:Home:index }

adena_mail_sender:
    path:     /sender
    defaults: { _controller: AdenaMailBundle:Sender:index }

adena_mail_sender_add:
    path:     /sender/add
    defaults: { _controller: AdenaMailBundle:Sender:add }
