adena_mail_homepage:
    path:     /
    defaults: { _controller: AdenaMailBundle:Home:index }

adena_mail_senders:
    path:     /senders
    defaults: { _controller: AdenaMailBundle:Senders:index }

adena_mail_email_add:
  path: /email/add
  defaults:
    _controller: AdenaMailBundle:Email:add

adena_mail_email_view:
  path: /email/{id}
  defaults:
    _controller: AdenaMailBundle:Email:view
  requirements:
    id: \d+

adena_mail_email_edit:
  path: /email/edit/{id}
  defaults:
    _controller: AdenaMailBundle:Email:edit
  requirements:
    id: \d+

adena_mail_email_delete:
  path: /email/delete/{id}
  defaults:
    _controller: AdenaMailBundle:Email:delete
  requirements:
    id: \d+

adena_mail_email_list:
  path: /email
  defaults:
    _controller: AdenaMailBundle:Email:list