services:
  foobar.form_extention.icon:
      class: Adena\MailBundle\Form\Extension\ButtonTypeIconExtension
      tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }

  tool.encrypt:
      class: Adena\MailBundle\Tools\EncryptTool
      arguments: ['%secret%']

  adena_mail.doctrine_listener.sender_update:
      class: Adena\MailBundle\DoctrineListener\SenderListener
      arguments:
          - "@tool.encrypt"
      tags:
          - { name: doctrine.event_listener, event: preUpdate }

  adena_mail.doctrine_listener.sender_creation:
      class: Adena\MailBundle\DoctrineListener\SenderListener
      arguments:
          - "@tool.encrypt"
      tags:
          - { name: doctrine.event_listener, event: prePersist }

  adena_mail.doctrine_listener.sender_load:
      class: Adena\MailBundle\DoctrineListener\SenderListener
      arguments:
          - "@tool.encrypt"
      tags:
          - { name: doctrine.event_listener, event: postLoad }
