services:
  foobar.form_extention.icon:
    class: Adena\MailBundle\Form\Extension\ButtonTypeIconExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }
