imports:
    - { resource: services/sender.yml }
    - { resource: services/datasource.yml }
    - { resource: services/action_control.yml }

services:
  adena_mail.form_extention.icon:
      class: Adena\MailBundle\Form\Extension\ButtonTypeIconExtension
      tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }

  adena_mail.form_extention.help_block:
        class: Adena\MailBundle\Form\Extension\HelpBlockExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

  adena_mail.datasource_can_connect_validator:
    class: Adena\MailBundle\Validator\Constraints\DatasourceCanConnectValidator
    tags:
      - { name: validator.constraint_validator }
    arguments:
      - "@adena_core.external_connection.mysql"

  adena_mail.campaign_can_send_email_validator:
      class: Adena\MailBundle\Validator\Constraints\CampaignCanSendEmailValidator
      tags:
        - { name: validator.constraint_validator }
      arguments:
        - "@adena_mail.entity_helper.campaign_tester"

  adena_mail.mailing_list_content_is_valid_validtor:
        class: Adena\MailBundle\Validator\Constraints\MailingListContentIsValidValidator
        tags:
          - { name: validator.constraint_validator }
        arguments:
          - "@adena_core.tool.csv_parser"
          - "@adena_core.external_connection.mysql"

  adena_mail.entity_helper.campaign_to_queue:
    class: Adena\MailBundle\EntityHelper\CampaignToQueue
    arguments:
      - "@doctrine.orm.default_entity_manager"
      - "@adena_mail.entity_helper.mailing_list_data_fetcher"

  adena_mail.entity_helper.mailing_list_data_fetcher:
    class: Adena\MailBundle\EntityHelper\MailingListDataFetcher
    arguments:
      - "@adena_core.external_connection.mysql"
      - '@adena_core.tool.csv_parser'

  adena_mail.entity_helper.mailing_list_tester:
    class: Adena\MailBundle\EntityHelper\MailingListTester
    arguments:
      - "@adena_core.external_connection.mysql"

  adena_mail.entity_helper.campaign_sender:
      class: Adena\MailBundle\EntityHelper\CampaignSender
      arguments:
        - "@doctrine.orm.default_entity_manager"
        - "@adena_mail.mail_engine"
        - "@adena_mail.entity_helper.campaign_to_queue"
        - "@adena_mail.action_control.campaign"
        - "@adena_mail.queue.queue_database_iterator"
        - "@twig"
        - "%kernel.logs_dir%"

  adena_mail.entity_helper.campaign_tester:
      class: Adena\MailBundle\EntityHelper\CampaignTester
      arguments:
        - '@twig'
        - '@adena_mail.entity_helper.mailing_list_data_fetcher'
        - '@adena_core.tool.background_runner'

  adena_mail.mail_engine:
      class: Adena\MailBundle\MailEngine\MailEngine
      arguments:
        - "@doctrine.orm.default_entity_manager"
        - "@logger"
        - "%kernel.logs_dir%"
      shared: false
      tags:
        - {name: "monolog.logger", channel: "mail_engine"}

  adena_mail.queue.queue_database_iterator:
    class: Adena\MailBundle\Queue\QueueDatabaseIterator
    arguments: ['@doctrine.orm.default_entity_manager']

  adena_mail.aceeditor_type:
    class: Adena\MailBundle\Form\Type\AceeditorType
    tags:
      - {name: form.type, alias: aceeditor}

  adena_mail.datetimepicker_type:
    class: Adena\MailBundle\Form\Type\DatetimepickerType
    tags:
      - {name: form.type, alias: datetimepicker}