imports:
    - { resource: services/sender.yml }
    - { resource: services/datasource.yml }
    - { resource: services/action_control.yml }

services:
  adena_mail.form_extention.icon:
      class: Adena\MailBundle\Form\Extension\ButtonTypeIconExtension
      tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }

  adena_mail.form_extention.help_block:
        class: Adena\MailBundle\Form\Extension\HelpBlockExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

  adena_mail.datasource_can_connect_validator:
    class: Adena\MailBundle\Validator\Constraints\DatasourceCanConnectValidator
    tags:
      - { name: validator.constraint_validator }
    arguments:
      - "@external_connection.mysql"

  adena_mail.entity_helper.campaign_to_queue:
    class: Adena\MailBundle\EntityHelper\CampaignToQueue
    arguments:
      - "@doctrine.orm.default_entity_manager"
      - "@adena_mail.entity_helper.mailing_list_emails_fetcher"

  adena_mail.entity_helper.mailing_list_emails_fetcher:
    class: Adena\MailBundle\EntityHelper\MailingListEmailsFetcher
    arguments:
      - "@external_connection.mysql"

  adena_mail.entity_helper.mailing_list_tester:
    class: Adena\MailBundle\EntityHelper\MailingListTester
    arguments:
      - "@external_connection.mysql"

  adena_mail.entity_helper.campaign_sender:
      class: Adena\MailBundle\EntityHelper\CampaignSender
      arguments:
        - "@doctrine.orm.default_entity_manager"
        - "@adena_mail.mail_engine"
        - "@adena_mail.entity_helper.campaign_to_queue"
        - "@adena_mail.action_control.campaign"
        - "@adena_mail.queue.queue_database_iterator"
        - "%kernel.logs_dir%"

  adena_mail.mail_engine:
      class: Adena\MailBundle\MailEngine\MailEngine
      arguments:
        - "@doctrine.orm.default_entity_manager"
        - "%kernel.logs_dir%"
      shared: false

  adena_mail.queue.queue_database_iterator:
    class: Adena\MailBundle\Queue\QueueDatabaseIterator
    arguments: ['@doctrine.orm.default_entity_manager']