<?php

namespace Adena\TestBundle\Tests\Repository;

/**
 * FixturesLoaderTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FixturesLoaderTestRepository extends \Doctrine\ORM\EntityRepository
{
}
