services:
  tool.encrypt:
      class: Adena\CoreBundle\Tools\EncryptTool
      arguments: ['%secret%']
  external_connection.mysql:
      class: Adena\CoreBundle\ExternalConnection\MysqlExternalConnection
      shared: false